name: build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"
      - "entrypoint.sh"
  workflow_run:
    workflows: ["pre-build"]
    types:
      - completed

jobs:
  build-v1:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push BASE
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64, linux/s390x, linux/ppc64le, linux/arm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-instant-ai